### ISSUE TITLE
Not sure if this is an issue

### ISSUE THREAD

**Issue by enchance** [rebaz94/lexo_rank_generator#1]
@rebaz94 I'm not sure if this is an issue or a limitation of firestore but shouldn't the order be something else?

```
// Format: {id}. {rank}
4. aaz
2. aaza
1. aazan   --> previously ccc and wanted to put it between 4 and 2 which gave "aazan"
```

Also tested this with Isar db and it got the same result.

The query:
```dart
var fs = FirebaseFirestore.instance;
fs.collection('foo').orderBy('rank').get()
  .then((res) {
    res.docs.forEach((DocumentSnapshot item) {
      Map data = item.data() as Map<String, dynamic>;
      print('${data['num']}:${data['rank']}');
    });
  });
```

**Comment by rebaz94** [comment]
Hi @enchance 
Thank you for issue, maybe there is a bug. but one question how you generate the rank? why `aaz` is 3 character but `aaza` is 4 character?

When you generate a rank, if the length is not equal it will add `a` character until both rank have equal length. in this case you generating rank between `aaza` and `aaza` which is same rank. maybe I should throw error if both rank is equal.

if you ensure both rank is same length, it will generate correctly.
```dart
print(lexoRank.getRankBetween(firstRank: 'aaaz', secondRank: 'aaza')); // aamz
print(['aaza', 'aaaz', 'aamz']..sort()); // [aaaz, aamz, aaza]
```

**Comment by enchance** [comment]
I must admit I was recklessly running several values to test its accuracy. It's possible this scenario might never arise as I randomly chose areas which might never have come up considering the length is checked.

Regarding the use of `generateInitialRank()` for rebalancing, how often do you think should it be run?

I also created a next rank generator for this purpose as well. What do you think?

```dart
String nextLexoRank(String base, [int incr=6]) {
  int lastUnit = base.toLowerCase().codeUnits[base.length - 1];
  // 122 is a 'z'
  if(lastUnit > 122 - incr) return base + 'a';

  var newchar = String.fromCharCode(lastUnit + incr);
  var retainstr = base.substring(0, base.length - 1);

  return retainstr + newchar;
}
```

**Comment by rebaz94** [comment]
`generateInitialRank` used to generate short rank values.
for example if you have 3 rank values like: `a, b, c` and if you reorder the position of rank too much, the size of rank will increase each time if there is not possible value between two rank. for example if you reorder 50 times between two rank like `a` and `b` 

check this:
```dart
  final ranks = <String, String>{};
  final String first = 'a';
  String second = 'b';

  for (int i = 0; i < 50; i++) {
    final rank = lexoRank.getRankBetween(firstRank: first, secondRank: second); // an
    ranks['$first-$second'] = rank;
    second = rank;
  }

  print(ranks.entries.map((e) => '${e.key}: ${e.value}').join('\n'));
  final values = ranks.values.toList();
  final shouldRebalanced = lexoRank.shouldRebalanced(
    values,
    maxRankLength: 5,
  );
  print('should rebalanced: ${shouldRebalanced.exceeded}, exceeded:${shouldRebalanced.exceededPercent}');

```

it generates 
```
a-b: an
a-an: ag
a-ag: ad
a-ad: ab
a-ab: aan
a-aan: aag
a-aag: aad
a-aad: aab
a-aab: aaan
a-aaan: aaag
a-aaag: aaad
a-aaad: aaab
a-aaab: aaaan
a-aaaan: aaaag
a-aaaag: aaaad
a-aaaad: aaaab
a-aaaab: aaaaan
a-aaaaan: aaaaag
a-aaaaag: aaaaad
a-aaaaad: aaaaab
a-aaaaab: aaaaaan
a-aaaaaan: aaaaaag
a-aaaaaag: aaaaaad
a-aaaaaad: aaaaaab
a-aaaaaab: aaaaaaan
a-aaaaaaan: aaaaaaag
a-aaaaaaag: aaaaaaad
a-aaaaaaad: aaaaaaab
a-aaaaaaab: aaaaaaaan
a-aaaaaaaan: aaaaaaaag
a-aaaaaaaag: aaaaaaaad
a-aaaaaaaad: aaaaaaaab
a-aaaaaaaab: aaaaaaaaan
a-aaaaaaaaan: aaaaaaaaag
a-aaaaaaaaag: aaaaaaaaad
a-aaaaaaaaad: aaaaaaaaab
a-aaaaaaaaab: aaaaaaaaaan
a-aaaaaaaaaan: aaaaaaaaaag
a-aaaaaaaaaag: aaaaaaaaaad
a-aaaaaaaaaad: aaaaaaaaaab
a-aaaaaaaaaab: aaaaaaaaaaan
a-aaaaaaaaaaan: aaaaaaaaaaag
a-aaaaaaaaaaag: aaaaaaaaaaad
a-aaaaaaaaaaad: aaaaaaaaaaab
a-aaaaaaaaaaab: aaaaaaaaaaaan
a-aaaaaaaaaaaan: aaaaaaaaaaaag
a-aaaaaaaaaaaag: aaaaaaaaaaaad
a-aaaaaaaaaaaad: aaaaaaaaaaaab
a-aaaaaaaaaaaab: aaaaaaaaaaaaan
a-aaaaaaaaaaaaan: aaaaaaaaaaaaag
```

so depend on your application you could periodically check if rank should rebalanced or not.

if your issue solved, please close the issue.
Thank you
